# Have the wrong order: First the custom resources, then their definitions. Let
# one of the the resource be a cluster resource, so that the Stack's resource
# reordering won't let the CRD go before the CR.

---
apiVersion: k0s.example.com/v1
kind: Character
metadata:
  name: frodo
  namespace: shire
spec:
  speciesRef:
    name: hobbit

---
apiVersion: k0s.example.com/v1
kind: Species
metadata:
  name: hobbit
spec:
  characteristics: hairy feet

---
apiVersion: v1
kind: Namespace
metadata:
  name: shire

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: species.k0s.example.com
spec:
  group: k0s.example.com
  names:
    kind: Species
    singular: species
    plural: species
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                characteristics:
                  type: string

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: characters.k0s.example.com
spec:
  group: k0s.example.com
  names:
    kind: Character
    singular: character
    plural: characters
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                speciesRef:
                  type: object
                  properties:
                    name:
                      type: string
